# Generated by Django 3.0.4 on 2020-08-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubtoStudentMap',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('att_value', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('end_sem_score', models.FloatField(default=0.0)),
                ('mid_sem_score', models.FloatField(default=0.0)),
                ('cia1_score', models.FloatField(default=0.0)),
                ('cia2_score', models.FloatField(default=0.0)),
                ('cia3_score', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Student')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='SubToClassMap',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Classroom')),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.Subjects')),
            ],
        ),
    ]
