# Generated by Django 3.0.4 on 2020-08-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_subjects_subtoclassmap_subtostudentmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_att',
            field=models.FloatField(default=0),
        ),
    ]
